# Generated by Django 5.1.15 on 2026-07-14 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion_corta', models.CharField(max_length=255, verbose_name='Descripción Corta')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción Detallada')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual')),
                ('cobertura_maxima', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cobertura Máxima')),
                ('categoria', models.CharField(choices=[('AUTO', 'Seguro de Auto'), ('HOGAR', 'Seguro de Hogar'), ('VIDA', 'Seguro de Vida'), ('SALUD', 'Seguro de Salud'), ('TECNOLOGIA', 'Seguro de Tecnología')], default='AUTO', max_length=20, verbose_name='Categoría')),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen')),
                ('icon_class', models.CharField(default='shield', max_length=50, verbose_name='Icono (Lucide/FontAwesome)')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Contratación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio de Cobertura')),
                ('precio_pactado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Pactado')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PENDIENTE', 'Pendiente de Pago'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='seguros.seguro', verbose_name='Seguro')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
